version: '3.5'
services:
  mysql:
    image: mysql:5.7.12
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "booking"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "123456"
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']